### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by dguo** [fiatjaf/search-comparison#3]
Hi, this website doesn't load for me (in both Firefox and Chrome) because of an SSL issue:

```
fiatjaf.alhur.es uses an invalid security certificate. 

The certificate is only valid for the following names: www.github.com, *.github.com, github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com

Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

**Comment by fiatjaf** [comment]
Oops. Try http://fiatjaf.alhur.es/search-comparison/.

**Comment by dguo** [comment]
It seems that there is an automatic redirect from the http version to the https version.

I'm able to bypass the warning in Chrome. Just wanted to give you a heads up about the issue.

**Comment by fiatjaf** [comment]
Use https://fiatjaf.github.io/search-comparison/ and pray to not be redirected.
